version: "3.8"
services:
  api:
    container_name: gpt-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    env_file:
      - stack.env
    pull_policy: build
    networks:
      - default

networks:
  default:
    external:
      name: bridge
