version: "3.8"
services:
  api:
    container_name: gpt-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    env_file:
      - ./.env
    pull_policy: build
    healthcheck:
      start_period: 10m
